on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: goatwu1993/release-please-action@1bf46c21bfa73fe0cb2f716e4a57821922b02dc6
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}
          extra-files: |
            README.md
