on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: goatwu1993/release-please-action@34d9e9e3af8527cd341451fe508bab081659f3e3
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}
          extra-files:  |
            README.md
