on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: jcornaz/release-please@feat/extra-files
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}
          extraFiles: |
            README.md
