on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: goatwu1993/release-please-action@b094977a5f7370637a936ba1d440c77b026a002f
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}
          extra-files:
            - README.md
